services:
  api:
    build: 
      context: .
      args:
        - DATABASE_URL=${DATABASE_URL}
        
    ports:
      - "4000:3000"
    env_file:
      - beta.env
    platform: linux/arm64
   
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgrespassword}
      POSTGRES_DB: ${DB_NAME:-opher-embedd}
    ports:
      - "5441:5432"
    

